### PR TITLE
refactor(lnurl-auth): better user pairing with `LnurlAuthUserPairingService`

### LINKED ISSUE #112: SimpleLinkingKey not found when used in spring boot starter.
I'm building a Spring boot starter including `spring-lnurl-auth-starter`.

In my spring boot starter tests, I can do this: 
```java
LinkingKey linkingKeyTest1 = SimpleLinkingKey.fromHex("02c3b844b8104f0c1b15c507774c9ba7fc609f58f343b9b149122e944dd20c9362");`
```

In my spring boot starter code, I can't do the same thing:
```java
LinkingKey linkingKeyTest1 = SimpleLinkingKey.fromHex("02c3b844b8104f0c1b15c507774c9ba7fc609f58f343b9b149122e944dd20c9362");`
```

because I get this error: `java: package org.tbk.lnurl.simple.auth does not exist`

I'm forced to add this to my POM:
```xml
<dependency>
   <groupId>io.github.theborakompanioni</groupId>
   <artifactId>lnurl-simple</artifactId>
   <version>0.11.0</version>
</dependency>
```

### LINKED ISSUE #122: ClassCastException when using @AuthenticationPrincipal
I have a spring boot controller with that code:
```
@GetMapping("/account/settings")
@PreAuthorize("isAuthenticated()")
public String displayAccountSettings(final Model model,
                                         final @AuthenticationPrincipal(errorOnInvalidType = true) UserDetails currentUser) {
        Optional<UserDTO> connectedUser = userService.getUserByUsername(currentUser.getUsername());
```

I get this error: `java.lang.ClassCastException: 028acfe2a7c5444a5872968f628d8fc827c32f7b11761e094818ee10ceeee9c5eb is not assignable to interface org.springframework.security.core.userdetails.UserDetails`

It seems your starter is not passing the userDetails but the linkingkey ?

### PR DESCRIPTION
**Pull request by theborakompanioni**
Resolves #112.
Fixes #122.

**Note**: This is a breaking change!

Replaces `LnurlAuthPairingService` with `LnurlAuthUserPairingService`.
This should make it more clear what a downstream implementation should provide and has more flexibility regarding persistence.
e.g. before a user has always been retrieved with `UserDetailsService#loadUserByUsername`.

### CODE REVIEW

**Comment by theborakompanioni** [comment]
@straumat can you look over the changes and report if that would serve your needs? :pray:

**Comment by straumat** [comment]
@theborakompanioni yes, i just wait for https://github.com/theborakompanioni/bitcoin-spring-boot-starter/issues/118 to implement it

**Comment by straumat** [comment]
is there a build on a repository I could use to make my test?

**Comment by theborakompanioni** [comment]
> is there a build on a repository I could use to make my test?

`refactor~lnurl-auth-pairing-service-SNAPSHOT` - still building though :sweat_smile:

**Comment by straumat** [comment]
@theborakompanioni great! Will try to implement it this week-end

**Comment by theborakompanioni** [comment]
> @theborakompanioni great! Will try to implement it this week-end

Great - with your approval, I will merge it release `v0.13.0` soon. :raised_hands:

**Comment by straumat** [comment]
Thanks for the update. I plan to try the latest release on monday.
The blog post is out : https://lab.scub.net/authentication-made-simple-with-bitcoin-java-5cb07c883b5f?fbclid=IwAR2SO6oXcJ1BSBFRmNUppLFl2JmOB-BqO99mMuXYXwFgj5wEasPAqzTf6mk

**Comment by theborakompanioni** [comment]
> Thanks for the update. I plan to try the latest release on monday. The blog post is out : https://lab.scub.net/authentication-made-simple-with-bitcoin-java-5cb07c883b5f?fbclid=IwAR2SO6oXcJ1BSBFRmNUppLFl2JmOB-BqO99mMuXYXwFgj5wEasPAqzTf6mk

:orange_heart: :muscle:

**Comment by straumat** [comment]
HI. I think I might need some help on my unit tests:

In my [UserDetailsServiceTest](https://github.com/royllo/explorer/blob/7b378557753c2002b995f1f79c0251549ea6b1fd/backend/explorer-core/autoconfigure/src/test/java/org/royllo/explorer/core/test/core/service/user/UserDetailsServiceTest.java#L42), I'm testing my `loadUserByUsername` method

I used to simulate a [lnurlAuthPairingService.pairK1WithLinkingKey(user1K1Test1, user1LinkingKeyTest1);](https://github.com/royllo/explorer/blob/7b378557753c2002b995f1f79c0251549ea6b1fd/backend/explorer-core/autoconfigure/src/test/java/org/royllo/explorer/core/test/core/service/user/UserDetailsServiceTest.java#L42)
That would create a user. how can I do it now ?

**Comment by straumat** [comment]
Sorry, i forgot to push my code. I implemented the new methods [here](https://github.com/royllo/explorer/blob/421af054e9c650cb761c989934528a2663a2cd5b/backend/explorer-core/autoconfigure/src/main/java/org/royllo/explorer/core/service/user/UserServiceImplementation.java#L137) and [there](https://github.com/royllo/explorer/blob/421af054e9c650cb761c989934528a2663a2cd5b/backend/explorer-core/autoconfigure/src/main/java/org/royllo/explorer/core/service/user/UserServiceImplementation.java#L170).

But in my [unit test](https://github.com/royllo/explorer/blob/development/backend/explorer-core/autoconfigure/src/test/java/org/royllo/explorer/core/test/core/service/user/UserDetailsServiceTest.java), i have to call `pairK1WithLinkingKey()` with a `SignedLnurlAuth` 
To do so,  : `create(LnurlAuth lnurlAuth, LinkingKey linkingKey, Signature signature)`
In my test, what parameters should I give to the create method that would work ?

**Comment by straumat** [comment]
I tried this, what do you think for a unit test:
```
// New user.
String user1K1Value = "e2af6254a8df433264fa23f67eb8188635d15ce883e8fc020989d5f82ae6f11e";
String user1linkingKey1Value = "02c3b844b8104f0c1b15c507774c9ba7fc609f58f343b9b149122e944dd20c9362";
K1 user1K1Test1 = SimpleK1.fromHex(user1K1Value);
LinkingKey user1LinkingKeyTest1 = SimpleLinkingKey.fromHex(user1linkingKey1Value);

// We create a new user.
SimpleLnurlAuth simpleLnurlAuth = SimpleLnurlAuth.create(new URI("http://locahost"), user1K1Test1);
Signature signature = SimpleSignature.fromHex("3046022100cd9f98eb6cda6d0b5f479a1709baed16d8e09e49a697d1f2a5315b933b29ff65022100983e4c03206656c67d849c142d55d7c6c80ec70b87a01bbffa6fb71464381b4e");
SignedLnurlAuth user1SignedLnurlAuth = SimpleSignedLnurlAuth.create(simpleLnurlAuth, user1LinkingKeyTest1, signature);
lnurlAuthPairingService.pairUserWithK1(user1SignedLnurlAuth);
```

**Comment by straumat** [comment]
maybe you should take a look at https://github.com/theborakompanioni/bitcoin-spring-boot-starter/issues/122 before releasing

**Comment by straumat** [comment]
It works! you can release!

**Pull request merged**
